"""
FastAPI application for the Text-to-Speech API.

Provides endpoints for listing available voices and generating speech audio
with sentence-level timestamps using Microsoft Edge neural TTS voices.

Parallelism model: the client fans out one POST /api/tts/fold per section.
Each request generates one fold in-process (long folds chunk internally via
asyncio.gather + ffmpeg merge in tts.py), so folds complete independently
and the first finished fold can play while the rest are still generating.
No task queue, no Redis — the fan-out is the parallel pipeline.
"""

import base64
import json
import logging
import os

from dotenv import load_dotenv

from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from tts import generate_audio_chunked, get_preferred_voices
from text_structure import analyze_text_structure
from summaries import summarize_fold

load_dotenv()

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="oriyomi TTS API",
    description="Free text-to-speech using Microsoft Edge neural voices with sentence timestamps.",
    version="1.0.0",
)

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s: %(message)s")

# ---------------------------------------------------------------------------
# Supabase client (optional — falls back to in-memory counter when absent)
# ---------------------------------------------------------------------------
SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "")
_supabase = None
if SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY:
    from supabase import create_client
    _supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

# ---------------------------------------------------------------------------
# Global stats counter
# ---------------------------------------------------------------------------
# Words-folded counter backed by Supabase when configured, otherwise in-memory
# (resets on server restart in the in-memory case).  Incremented by the word
# count of every successful TTS fold (/api/tts/fold, /api/tts).
_words_folded: int = 0


def _count_words(text: str) -> int:
    """Whitespace-delimited word count — the unit of the words-folded stat."""
    return len(text.split())


def _increment_words_folded(n: int) -> None:
    """Persist word count to Supabase. Falls back to in-memory on failure."""
    global _words_folded
    if _supabase is not None:
        try:
            _supabase.rpc("increment_words_folded", {"n": n}).execute()
        except Exception:
            _words_folded += n
    else:
        _words_folded += n

def _cors_origins() -> list[str]:
    """Browser origins allowed to call the API directly.

    Default covers the local frontend on either localhost or 127.0.0.1.
    Override with ALLOWED_ORIGINS=comma,separated,origins (Docker compose sets this).
    When the Next.js proxy is used, the browser is same-origin and CORS is unused.
    """
    raw = os.environ.get(
        "ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000",
    )
    origins = [o.strip() for o in raw.split(",") if o.strip()]
    return origins or ["http://localhost:3000"]


app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins(),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def log_requests(request: Request, call_next):
    logger.info("%s %s", request.method, request.url.path)
    response = await call_next(request)
    return response


# ---------------------------------------------------------------------------
# Request / response models
# ---------------------------------------------------------------------------

class TTSRequest(BaseModel):
    """Request body for the TTS endpoint."""
    text: str = Field(..., min_length=1, max_length=50000, description="Text to synthesize.")
    voice: str = Field(
        default="en-US-EmmaMultilingualNeural",
        description="Voice short name (e.g. 'en-US-EmmaMultilingualNeural').",
    )
    speed: float = Field(
        default=1.0,
        ge=0.5,
        le=2.0,
        description="Speech rate multiplier (0.5 = half speed, 2.0 = double speed).",
    )


class SentenceTimestamp(BaseModel):
    """Timing for a single sentence."""
    index: int = 0
    text: str
    start_ms: int
    end_ms: int


class TTSResponse(BaseModel):
    """Response from the TTS endpoint."""
    audio_base64: str = Field(description="Base64-encoded MP3 audio.")
    sentences: list[SentenceTimestamp] = Field(description="Sentence-level timestamps.")
    voice: str
    speed: float


class FoldTTSRequest(BaseModel):
    """One fold of a document, generated by a parallel client-side fan-out."""
    text: str = Field(..., min_length=1, max_length=50000)
    voice: str = Field(default="en-US-EmmaMultilingualNeural")
    speed: float = Field(default=1.0, ge=0.5, le=2.0)
    fold_index: int = Field(default=0, ge=0)
    title: str = ""


class DocumentFoldResult(BaseModel):
    """Audio + timings for a single completed fold."""
    fold_index: int
    title: str
    audio_base64: str
    sentences: list[SentenceTimestamp]
    voice: str
    speed: float
    duration_ms: int


class VoiceResponse(BaseModel):
    """A single voice in the voices list."""
    id: str
    name: str
    locale: str
    display_name: str


class StatsResponse(BaseModel):
    """Global usage statistics."""
    words_folded: int = Field(description="Total words successfully folded into speech since last server restart.")


# ---------------------------------------------------------------------------
# Structure analysis models
# ---------------------------------------------------------------------------

class AnalyzeRequest(BaseModel):
    """Request body for the structure analysis endpoint."""
    text: str = Field(..., min_length=1, max_length=50000, description="Text to analyze for structure.")


class AnalyzeSection(BaseModel):
    """A single section in the document structure."""
    title: str
    level: int
    section_type: str
    number: str | None
    char_start: int
    char_end: int
    text: str
    text_preview: str
    summary: str | None = Field(
        default=None,
        description="Extractive 2-3 sentence summary of this fold's text.",
    )
    children: list["AnalyzeSection"] = []


class AnalyzeResponse(BaseModel):
    """Response from the structure analysis endpoint."""
    sections: list[AnalyzeSection]
    doc_type: str  # "flat", "chapters", "sections", "hierarchical"
    total_chars: int
    detection_method: str
    has_structure: bool


# ---------------------------------------------------------------------------
# Quiz models
# ---------------------------------------------------------------------------

class QuizRequest(BaseModel):
    """Request body for the quiz endpoint."""
    text: str = Field(..., min_length=50, max_length=20000, description="Source text to generate questions from.")
    num_questions: int = Field(default=3, ge=1, le=8, description="How many questions to generate.")


class QuizQuestion(BaseModel):
    """A single multiple-choice quiz question."""
    question: str
    options: list[str]  # exactly 4
    correct_index: int  # 0-3
    explanation: str


class QuizResponse(BaseModel):
    """Response from the quiz endpoint."""
    questions: list[QuizQuestion]
    model: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

def _sentence_models(result) -> list[SentenceTimestamp]:
    return [
        SentenceTimestamp(index=i, text=s.text, start_ms=s.start_ms, end_ms=s.end_ms)
        for i, s in enumerate(result.sentences)
    ]


@app.get("/api/voices", response_model=list[VoiceResponse])
async def list_voices():
    """Return the highest-quality US English TTS voices, best first."""
    voices = await get_preferred_voices()
    return [
        VoiceResponse(id=v.id, name=v.name, locale=v.locale, display_name=v.display_name)
        for v in voices
    ]


@app.post("/api/analyze", response_model=AnalyzeResponse)
async def analyze_structure(request: AnalyzeRequest):
    """
    Analyze text for document structure (chapters, sections, subsections).

    Returns a tree of detected sections with character offsets, allowing the
    frontend to offer section-level TTS generation.
    """
    logger.info("Analyze request: %d chars", len(request.text))

    result = analyze_text_structure(request.text)

    def convert_section(s) -> AnalyzeSection:
        return AnalyzeSection(
            title=s.title,
            level=s.level,
            section_type=s.section_type,
            number=s.number,
            char_start=s.char_start,
            char_end=s.char_end,
            text=s.text,
            text_preview=s.text_preview,
            summary=summarize_fold(s.text),
            children=[convert_section(c) for c in s.children],
        )

    return AnalyzeResponse(
        sections=[convert_section(s) for s in result.sections],
        doc_type=result.doc_type,
        total_chars=result.total_chars,
        detection_method=result.detection_method,
        has_structure=result.has_structure,
    )


@app.post("/api/tts", response_model=TTSResponse)
async def text_to_speech(request: TTSRequest):
    """
    Generate speech audio from text.

    Always synchronous: long texts chunk internally and generate in parallel
    inside this request (see tts.generate_audio_chunked), then merge.
    """
    logger.info(
        "TTS request: text=%d chars, voice=%s, speed=%.1f",
        len(request.text), request.voice, request.speed,
    )

    try:
        result = await generate_audio_chunked(
            text=request.text,
            voice=request.voice,
            speed=request.speed,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=f"TTS generation failed: {e}")
    except HTTPException:
        raise
    except Exception as e:
        # Anything else (missing binary, OOM, …) — return JSON so clients
        # surface the message instead of dying on a plain-text 500 body.
        logger.exception("Unexpected TTS failure")
        raise HTTPException(status_code=500, detail=f"TTS generation failed: {e}")

    _increment_words_folded(_count_words(request.text))

    return TTSResponse(
        audio_base64=base64.b64encode(result.audio_bytes).decode("utf-8"),
        sentences=_sentence_models(result),
        voice=request.voice,
        speed=request.speed,
    )


@app.post("/api/tts/fold", response_model=DocumentFoldResult)
async def tts_fold(request: FoldTTSRequest):
    """
    Generate one fold's audio.

    The client fires these in parallel — one request per fold — so folds
    generate concurrently and the first completed fold can play while the
    rest are still running. Long folds chunk internally, in-process.
    """
    title = request.title or f"Fold {request.fold_index + 1:02d}"
    logger.info(
        "Fold TTS: index=%d title=%r text=%d chars",
        request.fold_index, title, len(request.text),
    )

    try:
        result = await generate_audio_chunked(
            text=request.text,
            voice=request.voice,
            speed=request.speed,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=f"TTS generation failed: {e}")
    except HTTPException:
        raise
    except Exception as e:
        # Anything else (missing binary, OOM, …) — return JSON so clients
        # surface the message instead of dying on a plain-text 500 body.
        logger.exception("Unexpected TTS failure")
        raise HTTPException(status_code=500, detail=f"TTS generation failed: {e}")

    duration_val = result.sentences[-1].end_ms if result.sentences else 0

    _increment_words_folded(_count_words(request.text))

    return DocumentFoldResult(
        fold_index=request.fold_index,
        title=title,
        audio_base64=base64.b64encode(result.audio_bytes).decode("utf-8"),
        sentences=_sentence_models(result),
        voice=request.voice,
        speed=request.speed,
        duration_ms=duration_val,
    )


@app.post("/api/quiz", response_model=QuizResponse)
async def generate_quiz(request: QuizRequest):
    """
    Generate multiple-choice quiz questions about the given text using Google Gemini.

    Returns a strict-JSON list of questions, each with 4 options and a correct index.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise HTTPException(
            status_code=503,
            detail="GEMINI_API_KEY is not set. Copy .env.example to .env and add your Google Gemini API key.",
        )

    model_name = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
    logger.info(
        "Quiz request: text=%d chars, num_questions=%d, model=%s",
        len(request.text), request.num_questions, model_name,
    )

    prompt = (
        f"You are a quiz generator. Based on the source text below, create exactly "
        f"{request.num_questions} multiple-choice questions that test comprehension of the material.\n\n"
        "Return STRICT JSON only — no markdown, no code fences, no extra commentary. "
        "The JSON must match this shape exactly:\n"
        '{"questions": [{"question": str, "options": [4 strings], "correct_index": int, "explanation": str}]}\n\n'
        "Rules:\n"
        "- Each question must have exactly 4 options.\n"
        "- Exactly one option is correct; correct_index is the 0-based index of that option.\n"
        "- Shuffle option order so the correct answer is not always in the same position.\n"
        "- The explanation should briefly justify why the correct answer is right.\n"
        "- Do not include any keys other than those specified.\n\n"
        f"Source text:\n{request.text}"
    )

    from google import genai
    client = genai.Client(api_key=api_key)
    try:
        result = client.models.generate_content(
            model=model_name,
            contents=prompt,
        )
    except Exception as e:
        logger.error("Gemini API call failed: %s", e)
        raise HTTPException(status_code=502, detail=f"Gemini API call failed: {e}")

    raw = result.text or ""

    # Defensive JSON parsing: strip markdown fences if present
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        # Remove opening fence (```json or ```) and closing fence
        lines = cleaned.split("\n")
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        cleaned = "\n".join(lines).strip()

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as e:
        logger.error("Quiz JSON parse failed: %s | raw=%.300s", e, raw)
        raise HTTPException(
            status_code=502,
            detail=f"Model returned invalid JSON: {raw[:300]}",
        )

    raw_questions = data.get("questions", [])
    if not isinstance(raw_questions, list) or not raw_questions:
        raise HTTPException(status_code=502, detail=f"Model returned no questions: {raw[:300]}")

    questions: list[QuizQuestion] = []
    for i, q in enumerate(raw_questions):
        try:
            options = q["options"]
            correct_index = int(q["correct_index"])
            if len(options) != 4:
                raise ValueError(f"question {i}: expected 4 options, got {len(options)}")
            if not (0 <= correct_index < 4):
                raise ValueError(f"question {i}: correct_index {correct_index} out of range")
            questions.append(QuizQuestion(
                question=str(q["question"]),
                options=[str(o) for o in options],
                correct_index=correct_index,
                explanation=str(q.get("explanation", "")),
            ))
        except (KeyError, TypeError, ValueError) as e:
            logger.error("Quiz question validation failed at index %d: %s | raw=%.300s", i, e, raw)
            raise HTTPException(status_code=502, detail=f"Invalid question from model: {e}")

    logger.info("Quiz generated: %d questions from model %s", len(questions), model_name)
    return QuizResponse(questions=questions, model=model_name)


@app.get("/api/health")
async def health():
    """Health check endpoint."""
    return {"status": "ok"}


@app.get("/api/stats", response_model=StatsResponse)
async def stats():
    """Return global usage stats (Supabase-backed, in-memory fallback)."""
    if _supabase is not None:
        try:
            result = _supabase.table("stats").select("words_folded").limit(1).execute()
            if result.data:
                return StatsResponse(words_folded=int(result.data[0]["words_folded"]))
        except Exception:
            pass
    return StatsResponse(words_folded=_words_folded)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
